name: Update Pokemon Cards

on:
  schedule:
    - cron: '0 0 1 * *' # tous les 1ers du mois à minuit
  workflow_dispatch: # permet un déclenchement manuel

jobs:
  update-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Fetch all cards (db.json)
        run: node fetchCards.js

      - name: Format cards (PokemonCards.json)
        run: node formatCards.js

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add PokemonCards.json
          git diff --cached --quiet || git commit -m "Update Pokemon cards [skip ci]"
          git push
